{
 "title": "Server 114 Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Log size",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "log_directory_size_bytes / 1024^3\r\n",
     "legendFormat": "{{exported_service}}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "disk_usage_bytes{partition=\"/\"} / 1024^3",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Trend usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 1 },
   "targets": [
    {
     "expr": "disk_usage_bytes{partition=\"/\",type=\"used\"} / 1024^3",
     "legendFormat": "{{service}}"
    }
   ]
  },
  { "title": "Localization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Total Global Request",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({job=\"nginx_geoip\"} [$__range]))"
    }
   ]
  },
  {
   "title": "IP Client Access",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(10, sum by (remote_addr) (count_over_time({job=\"nginx_geoip\"} | json [$__range])))",
     "legendFormat": "{{remote_addr}}"
    }
   ]
  },
  {
   "title": "User Agent",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 10, "x": 7, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(10, sum by (http_user_agent) (count_over_time({job=\"nginx_geoip\"} | json [$__range])))",
     "legendFormat": "{{htto_user_agent}}"
    }
   ]
  },
  {
   "title": "HTTP Method",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 7, "x": 17, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (request_method) (count_over_time({job=\"nginx_geoip\"} | json [$__range]))",
     "legendFormat": "{{request_method}}"
    }
   ]
  },
  {
   "title": "Client City",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(10, sum by (location) (count_over_time({job=\"nginx_geoip\"} | json | geoip_country != \"\" | label_format location=\"{{.geoip_city}} - {{.geoip_country}}\" [$__range])))",
     "legendFormat": "{{geoip_city}}"
    }
   ]
  },
  {
   "title": "Nginx Global Traffic",
   "type": "geomap",
   "gridPos": { "h": 17, "w": 14, "x": 10, "y": 25 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"nginx_geoip\"}"
    }
   ]
  },
  {
   "title": "Most requests",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 35 },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(10, sum by (ip_dettaglio) (\r\n    count_over_time({job=\"nginx_geoip\"} \r\n        | json \r\n        | geoip_country != \"\" \r\n        | label_format ip_dettaglio=\"{{.remote_addr}}: {{.geoip_city}} - {{.geoip_country}}\" \r\n        [$__range]\r\n    )\r\n))"
    }
   ]
  },
  { "title": "Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Attacker ips",
   "type": "table",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 43 },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(10, sum by (ip) (\r\n  count_over_time(\r\n    {job=\"modsecurity\"}\r\n    |~ \"ModSecurity: Access denied\"\r\n    | regexp `client\\s(?P<ip>[0-9a-fA-F:.]+)`\r\n    | ip != \"\"\r\n  [$__range])\r\n))",
     "legendFormat": "{{transaction_client_ip}}"
    }
   ]
  },
  {
   "title": "Total ip ban",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 43 },
   "targets": [
    { "expr": "sum(fail2ban_banned_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Health Check",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "up", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 15, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device=\"ens18\"}[5m]) / 1024 / 1024"
    }
   ]
  },
  {
   "title": "Used Memory Percentage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 17, "y": 43 },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes/node_memory_MemTotal_bytes) * 100)",
     "legendFormat": "Used Memory - {{instance}}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 43 },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Attacks",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 48 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"modsecurity\"}\r\n|~ \"ModSecurity\"\r\n|~ \"\\\\[id \\\"\"\r\n| regexp `id\\s\"(?P<rule_id>[0-9]+)\"`        \r\n| regexp `client\\W+(?P<ip>[0-9\\.]+)`        \r\n| line_format \"{ \\\"IP\\\": \\\"{{.ip}}\\\", \\\"RULE_ID\\\": \\\"{{.rule_id}}\\\" }\"\r\n| rule_id != \"949110\"                         "
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 3, "x": 9, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (job) (\r\n  rate(\r\n    {job=~\"nginx|auth|mysql|php-fpm\"} |~ \" 404 | 50[0-9]|error|Failed password|Access denied\"\r\n  [5m])\r\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Job Health Check",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 12, "y": 48 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(job) (rate({job=~\".+\"}[5m]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "CPU Usage ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 48 },
   "targets": [
    {
     "expr": "100 - (rate(node_cpu_seconds_total{mode=\"idle\"}[5m]) * 100)",
     "legendFormat": "CPU {{cpu}} - {{mode}}"
    }
   ]
  },
  {
   "title": "Authentication Failure (rate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "targets": [
    {
     "direction": "backward",
     "expr": "rate({job=\"auth\"} |= \"error\"[5m])"
    }
   ]
  },
  {
   "title": "Attack Type Distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (rule_id) (count_over_time({job=\"modsecurity\"} \r\n|~ \"ModSecurity\" \r\n|~ \"\\\\[id \\\"\" \r\n| regexp `id\\s\"(?P<rule_id>[0-9]+)\"` \r\n| rule_id != \"949110\" \r\n[$__range]))          ",
     "legendFormat": "{{rule_id}}"
    }
   ]
  },
  {
   "title": "Ban Ip",
   "type": "logs",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 63 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"fail2ban\"} |= \"Ban\""
    }
   ]
  },
  { "title": "Test run_test", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "Access denied (MySQL)",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"mysql\"} |= \"Access denied\""
    }
   ]
  },
  {
   "title": "Error 404",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"nginx\"}\r\n|= \"404\"\r\n"
    }
   ]
  },
  {
   "title": "Invalid User",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"auth\"}\r\n|~ \"Failed password|Invalid user\""
    }
   ]
  }
 ]
}